//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TjossSystem.Metodos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadastro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cadastro()
        {
            this.contrato = new HashSet<contrato>();
            this.dadosfisicos = new HashSet<dadosfisicos>();
            this.definicaocadastro = new HashSet<definicaocadastro>();
            this.medida = new HashSet<medida>();
            this.pedidos = new HashSet<pedidos>();
        }
    
        public int codigocadastro { get; set; }
        public string nomecadastro { get; set; }
        public string nomefantasia { get; set; }
        public int codigotipocadastro { get; set; }
        public string cpfcnpj { get; set; }
        public string controle { get; set; }
        public System.DateTime datahalteracao { get; set; }
        public int codigofuncionario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contrato> contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dadosfisicos> dadosfisicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<definicaocadastro> definicaocadastro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medida> medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidos> pedidos { get; set; }
        public virtual funcionarios funcionarios { get; set; }
        public virtual tipocadastro tipocadastro { get; set; }
    }
}
