//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TjossSystem.Metodos
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contrato()
        {
            this.itenscontrato = new HashSet<itenscontrato>();
            this.pedidos = new HashSet<pedidos>();
        }
    
        public int numerocontrato { get; set; }
        public int codigotipocontrato { get; set; }
        public int codigocadastro { get; set; }
        public System.DateTime datacontrato { get; set; }
        public System.DateTime datavencimento { get; set; }
        public string situacao { get; set; }
        public Nullable<int> codigovendedor { get; set; }
        public System.DateTime datahalteracao { get; set; }
        public int codigofuncionario { get; set; }
    
        public virtual cadastro cadastro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itenscontrato> itenscontrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidos> pedidos { get; set; }
        public virtual funcionarios funcionarios { get; set; }
        public virtual tipocontrato tipocontrato { get; set; }
    }
}
