//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TjossSystem.Metodos
{
    using System;
    using System.Collections.Generic;
    
    public partial class dadosfisicos
    {
        public int codigocadastro { get; set; }
        public int codigofilial { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public int numero { get; set; }
        public string complemento { get; set; }
        public string cependereco { get; set; }
        public Nullable<int> codigocidade { get; set; }
    
        public virtual cadastro cadastro { get; set; }
        public virtual cidade cidade { get; set; }
    }
}
