//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TjossSystem.Metodos
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemestoque
    {
        public int codigoitem { get; set; }
        public int codigotipoestoque { get; set; }
        public decimal quantidadedisponivel { get; set; }
        public decimal valorproduto { get; set; }
    
        public virtual itens itens { get; set; }
        public virtual tipoestoque tipoestoque { get; set; }
    }
}
