//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TjossSystem.Metodos
{
    using System;
    using System.Collections.Generic;
    
    public partial class itenscontrato
    {
        public int numerocontrato { get; set; }
        public int codigotipocontrato { get; set; }
        public int codigoitem { get; set; }
        public decimal saldocontratado { get; set; }
        public decimal saldoatual { get; set; }
    
        public virtual contrato contrato { get; set; }
        public virtual itens itens { get; set; }
    }
}
