//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TjossSystem.Metodos
{
    using System;
    using System.Collections.Generic;
    
    public partial class itens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public itens()
        {
            this.formulaitem = new HashSet<formulaitem>();
            this.itemestoque = new HashSet<itemestoque>();
            this.itenscontrato = new HashSet<itenscontrato>();
            this.itenspedido = new HashSet<itenspedido>();
        }
    
        public int codigoitem { get; set; }
        public string descricaoitem { get; set; }
        public int codigotipoitem { get; set; }
        public string situacao { get; set; }
        public System.DateTime datahalteracao { get; set; }
        public int codigofuncionario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formulaitem> formulaitem { get; set; }
        public virtual funcionarios funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemestoque> itemestoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itenscontrato> itenscontrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itenspedido> itenspedido { get; set; }
        public virtual tipoitem tipoitem { get; set; }
    }
}
