//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TjossSystem.Metodos
{
    using System;
    using System.Collections.Generic;
    
    public partial class itenspedido
    {
        public int numeropedido { get; set; }
        public int codigotipopedido { get; set; }
        public int codigoitem { get; set; }
        public decimal quantidadesolicitada { get; set; }
        public decimal quantidadebaixada { get; set; }
        public decimal valorunitario { get; set; }
        public decimal valortotalitem { get; set; }
        public Nullable<int> codigocadastro { get; set; }
        public Nullable<int> codigomedida { get; set; }
    
        public virtual itens itens { get; set; }
        public virtual medida medida { get; set; }
        public virtual pedidos pedidos { get; set; }
    }
}
