//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TjossSystem.Metodos
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimentoestoque
    {
        public int sequenciamovimentoestoque { get; set; }
        public int codigoitem { get; set; }
        public string tipomovimento { get; set; }
        public decimal quantidademovimentada { get; set; }
        public System.DateTime datahmovimento { get; set; }
        public int codigofuncionario { get; set; }
    
        public virtual funcionarios funcionarios { get; set; }
        public virtual itens itens { get; set; }
    }
}
