//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TjossSystem.Metodos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidos()
        {
            this.itenspedido = new HashSet<itenspedido>();
        }
    
        public int numeropedido { get; set; }
        public int codigotipopedido { get; set; }
        public int codigocadastro { get; set; }
        public string situacaopedido { get; set; }
        public System.DateTime dataconclusao { get; set; }
        public Nullable<int> numerocontrato { get; set; }
        public Nullable<int> codigotipocontrato { get; set; }
    
        public virtual cadastro cadastro { get; set; }
        public virtual contrato contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itenspedido> itenspedido { get; set; }
        public virtual tipopedido tipopedido { get; set; }
    }
}
