//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TjossSystem.Metodos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tjossEntities : DbContext
    {
        public tjossEntities()
            : base("name=tjossEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cadastro> cadastro { get; set; }
        public virtual DbSet<contrato> contrato { get; set; }
        public virtual DbSet<dadosfisicos> dadosfisicos { get; set; }
        public virtual DbSet<definicaocadastro> definicaocadastro { get; set; }
        public virtual DbSet<funcionarios> funcionarios { get; set; }
        public virtual DbSet<itemestoque> itemestoque { get; set; }
        public virtual DbSet<itens> itens { get; set; }
        public virtual DbSet<itenscontrato> itenscontrato { get; set; }
        public virtual DbSet<itenspedido> itenspedido { get; set; }
        public virtual DbSet<medida> medida { get; set; }
        public virtual DbSet<movimentoestoque> movimentoestoque { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<tipocadastro> tipocadastro { get; set; }
        public virtual DbSet<tipocontrato> tipocontrato { get; set; }
        public virtual DbSet<tipodefinicao> tipodefinicao { get; set; }
        public virtual DbSet<tipoestoque> tipoestoque { get; set; }
        public virtual DbSet<tipoitem> tipoitem { get; set; }
        public virtual DbSet<tipopedido> tipopedido { get; set; }
    }
}
